[package]
name = "pipauto"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
faker_rand = "0.1"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
surrealdb = "2.0"
thiserror = "1.0"
tokio = "1.40"
